version: "3.4"
services:
  centos6imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el6
  centos7imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
